name: midas-py311
channels:
  - pytorch
  - defaults
dependencies:
  - nvidia::cudatoolkit=12.1.0
  - python=3.11.0
  - pytorch::pytorch=1.13.0
  - torchvision=0.14.0
  - pip=22.3.1
  - numpy=1.23.4
  - pip:
    - opencv-python==4.6.0.66
    - imutils==0.5.4
    - timm==0.6.12
    - einops==0.6.0